-- ----------------------------------------------------------------------------
-- Keymaps
-- ----------------------------------------------------------------------------

vim.keymap.set({ "n", "x" }, "<leader>-", [[mzyyp^v$r-`zzzzv]], { remap = true })

-- ----------------------------------------------------------------------------
-- LSP Config
-- ----------------------------------------------------------------------------

-- return {
-- 	require("lspconfig").pyright.setup({
-- 		settings = {
-- 			python = {
-- 				analysis = {
-- 					autoSearchPaths = true,
-- 					diagnosticMode = "workspace",
-- 					typeCheckingMode = "off",
-- 					useLibraryCodeForTypes = true,
-- 					disableOrganizeImports = true,
-- 				},
-- 			},
-- 		},
-- 	}),

-- 	require("lspconfig").ruff.setup({
-- 		init_options = {
-- 			settings = {
-- 				enable = true,
-- 				fixAll = true,
-- 				lineLength = 79,
-- 				organizeImports = false,
-- 				showSyntaxErrors = true,
-- 				configurationPreference = "filesystemFirst",
-- 				codeAction = {
-- 					fixViolation = { enable = true },
-- 					disableRuleComment = { enable = true },
-- 				},
-- 				lint = {
-- 					select = {
-- 						"A",
-- 						"B",
-- 						"C4",
-- 						"D",
-- 						"E",
-- 						"F",
-- 						"N",
-- 						"W",
-- 						"DJ",
-- 						"PT",
-- 						"EM",
-- 						"UP",
-- 						"NPY",
-- 						"ISC",
-- 						"ICN",
-- 						"SIM",
-- 						"RUF",
-- 						"PERF",
-- 						"ASYNC",
-- 					},
-- 					ignore = {
-- 						"C408",
-- 						"D100",
-- 						"D101",
-- 						"D102",
-- 						"D103",
-- 						"D104",
-- 						"D105",
-- 						"D205",
-- 						"UP031",
-- 						"RUF022",
-- 						"ASYNC110",
-- 					},
-- 				},
-- 			},
-- 		},
-- 	}),
-- }
